[PATCH] Revert "[CodeHealth] Improve dictionary building in print_settings_conversion.cc"
| In file included from ../../components/services/app_service/public/cpp/permission.cc:9:
| ../../base/containers/to_value_list.h:39:46: error: no matching member function for call to 'Append'
|    39 |       [&]<typename T>(T&& value) { container.Append(std::forward<T>(value)); },
|       |                                    ~~~~~~~~~~^~~~~~
| /workdir/build-openstlinuxweston-stm32mp25-eval/tmp-glibc/work/cortexa35-ostl-linux/chromium-ozone-wayland/135.0.7049.114/recipe-sysroot/usr/include/c++/v1/__type_traits/invoke.h:341:10: note: in instantiation of function template specialization 'base::ToValueList(const std::vector<std::unique_ptr<apps::Permission>> &, base::Value::Dict (*)(const std::unique_ptr<apps::Permission> &))::(anonymous class)::operator()<base::Value::Dict &>' requested here
|   341 | decltype(std::declval<_Fp>()(std::declval<_Args>()...))

------

This reverts commit 2bb6cb3bda5ea414ee193ae004c92a4b01c133fa.

| In file included from ../../printing/print_settings_conversion.cc:19:
| ../../base/containers/to_value_list.h:39:46: error: no matching member function for call to 'Append'
|    39 |       [&]<typename T>(T&& value) { container.Append(std::forward<T>(value)); },
|       |                                    ~~~~~~~~~~^~~~~~
| /workdir/build-openstlinuxweston-stm32mp25-eval/tmp-glibc/work/cortexa35-ostl-linux/chromium-ozone-wayland/135.0.7049.114/recipe-sysroot/usr/include/c++/v1/__type_traits/invoke.h:341:10: note: in instantiation of function template specialization 'base::ToValueList(const std::vector<printing::PageRange> &, (lambda at ../../printing/print_settings_conversion.cc:373:46))::(anonymous class)::operator()<base::Value::Dict &>' requested here
|   341 | decltype(std::declval<_Fp>()(std::declval<_Args>()...))

Signed-off-by: Ariel D'Alessandro <ariel.dalessandro@collabora.com>