chromium: [PATCH] Revert "Set Rust symbol visibility to hidden when ..."
This reverts chromium commit ee3900fd57b3c580aefff15c64052904d81b7760.
* Change-Id: https://crrev.com/c/5966273

Fixes the following compilation error:

```
| FAILED: obj/third_party/rust/ryu/v1/lib/libryu_lib.rlib
[...]
| error: unknown unstable option: `default-visibility`
```

This patch will be dropped once Rust >= 1.83 is available, which
includes:
* rust-lang/rust#130005 [0]
* rust-lang/rust#131519 [1]

Note that currently meta-lts-mixins [2] provides the following versions:
* kirkstone: `1.80.1`
* scarthgap: `1.81.0`

[0] https://github.com/rust-lang/rust/pull/130005
[1] https://github.com/rust-lang/rust/pull/131519
[2] https://git.yoctoproject.org/meta-lts-mixins

Signed-off-by: Ariel D'Alessandro <ariel.dalessandro@collabora.com>