chromium: Revert "Introducing base::RelaxedAtomicWriteMemcpy"
| FAILED: obj/base/base/atomicops.o
| ../../base/atomicops.cc:20:22: error: no member named 'atomic_ref' in namespace 'std'
|    20 |   static_assert(std::atomic_ref<uint8_t>::required_alignment == 1);
|       |                 ~~~~~^

This reverts commit d29b01737a841b5627249d50f007dcdc7e26462b.

Signed-off-by: Ariel D'Alessandro <ariel.dalessandro@collabora.com>