chromium: [PATCH] Disable Rust log crate bindgen
This reverts chromium commit 7ea0a5e831dd5 ("Connect the Rust log crate
to the //base logging implementation".

The above commit enabled bindgen for the Rust logger. Similar to patch
0011-Disable-crabbyavif-to-fix-build-errors.patch added in commit [0],
this fixes a build error that's most likely because the way upstream
configures bindgen makes it incompatible with our cross-architecture
builds.

```
| FAILED: gen/base/logging_rust_log_integration_bindgen_generator/bindings.rs
| [...]
| panicked at bindgen-cli/main.rs:52:36:
| Unable to generate bindings: ClangDiagnostic("error: unsupported option '-mbranch-protection=' for target 'x86_64-unknown-linux-gnu'\n")
```

[0] meta-browser commit fd347dc ("chromium: Update to 127.0.6533.99")

Signed-off-by: Ariel D'Alessandro <ariel.dalessandro@collabora.com>